export type Language = "en" | "ar";

const translations = {
  en: {
    home: "Home", profile: "Profile", store: "Store", dailyPractice: "DAILY PRACTICE · 5 MINUTES", titleA: "Make your mind", titleB: "move faster.", subtitle: "Five sharp challenges. One clearer you.", playToday: "Play today’s challenge", freePlay: "Free to play · No forced ads", level: "LEVEL", streak: "STREAK", days: "days", todaysRoute: "TODAY’S ROUTE", routeTitle: "Five ways to wake up.", yourStats: "Your stats", comeBack: "COME BACK TOMORROW", smallReps: "Small reps. Big shifts.", nextMilestone: "Your next streak milestone is", day: "Day", exit: "Exit", hint: "Need a nudge?", hintLabel: "Hint", takeTime: "Take your time", basePoints: "+100 pts base", preferences: "PREFERENCES", makeYours: "Make it yours.", language: "Language", sound: "Sound effects", reducedMotion: "Reduced motion", on: "On", off: "Off", privacy: "Privacy & analytics", privacyCopy: "Anonymous events help improve the game.", privacyFoot: "No contacts, precise location, or sensitive data collected.", routeComplete: "ROUTE COMPLETE", niceWork: "Nice work,", brain: "brain.", showedUp: "You showed up. That’s the habit.", share: "Share result", playAgain: "Play again", backHome: "Back to home", profileTitle: "Alex’s brain map", playerProfile: "PLAYER PROFILE", achievements: "ACHIEVEMENTS", proof: "Proof of progress.", earned: "EARNED", shop: "THE MIND MAZE SHOP", invest: "Invest in your", focus: "focus.", optional: "Optional extras. The full game stays free.", featured: "Featured", coins: "Mind Coins", themes: "Themes", configReady: "Configuration ready", storeNote: "Payments and ad SDKs are not connected in this MVP."
  },
  ar: {
    home: "الرئيسية", profile: "الملف الشخصي", store: "المتجر", dailyPractice: "تدريب يومي · 5 دقائق", titleA: "اجعل عقلك", titleB: "أسرع حركة.", subtitle: "خمسة تحديات ذكية. نسخة أوضح منك.", playToday: "ابدأ تحدي اليوم", freePlay: "اللعب مجاني · لا إعلانات إجبارية", level: "المستوى", streak: "السلسلة", days: "أيام", todaysRoute: "مسار اليوم", routeTitle: "خمس طرق لإيقاظ عقلك.", yourStats: "إحصاءاتك", comeBack: "عد غدًا", smallReps: "خطوات صغيرة. تغييرات كبيرة.", nextMilestone: "المحطة التالية في سلسلتك هي", day: "اليوم", exit: "خروج", hint: "تحتاج مساعدة؟", hintLabel: "تلميح", takeTime: "خذ وقتك", basePoints: "+100 نقطة أساسية", preferences: "التفضيلات", makeYours: "خصص تجربتك.", language: "اللغة", sound: "المؤثرات الصوتية", reducedMotion: "حركة أقل", on: "مفعّل", off: "متوقف", privacy: "الخصوصية والتحليلات", privacyCopy: "الأحداث المجهولة تساعدنا على تحسين اللعبة.", privacyFoot: "لا نجمع جهات الاتصال أو الموقع الدقيق أو البيانات الحساسة.", routeComplete: "اكتمل المسار", niceWork: "أحسنت يا", brain: "عبقري.", showedUp: "لقد حضرت اليوم. هذه هي العادة.", share: "مشاركة النتيجة", playAgain: "العب مجددًا", backHome: "العودة للرئيسية", profileTitle: "خريطة عقل Alex", playerProfile: "ملف اللاعب", achievements: "الإنجازات", proof: "دليل تطورك.", earned: "مكتمل", shop: "متجر Mind Maze", invest: "استثمر في", focus: "تركيزك.", optional: "إضافات اختيارية. اللعبة الأساسية مجانية دائمًا.", featured: "مميز", coins: "عملات العقل", themes: "الثيمات", configReady: "جاهز للإعداد", storeNote: "الدفع والإعلانات غير موصولين في هذه النسخة التجريبية."
  }
} as const;

export function t(language: Language, key: keyof typeof translations.en): string {
  return translations[language][key] || translations.en[key];
}
